### PR TITLE
Improve code demos of day 5

### PR DESCRIPTION
**Pull request by tpielok**
- [x] Nested Resampling ([code_demo_nested.pdf](https://github.com/compstat-lmu/lecture_i2ml/files/3831136/code_demo_nested.pdf))
- [x]  Kaggle Challenge ([code_demo_kaggle.pdf](https://github.com/compstat-lmu/lecture_i2ml/files/3831137/code_demo_kaggle.pdf))

### CODE REVIEW

**Comment by fabian-s** [comment]
not merging this since we will move to mlr3 anyways --
also: would be nice to get a mote obvious overfit for simple CV, for didactic reasons.....

**Comment by fabian-s** [comment]
@tpielok just checking: movuing this to mlr3 is still open, correct?

**Comment by tpielok** [comment]
Yes, I'm currently moving day 4 to mlr3 and then I will start with day 5.

**Comment by tpielok** [comment]
The transition of the code demos of day 5 from mlr2 to mlr3 is complete.

rendered pdfs:
[code_demo_kaggle.pdf](https://github.com/compstat-lmu/lecture_i2ml/files/4318425/code_demo_kaggle.pdf)
[code_demo_nested.pdf](https://github.com/compstat-lmu/lecture_i2ml/files/4318426/code_demo_nested.pdf)

> also: would be nice to find an example with a more obviously "optimistic" generalization error for simple CV, for didactic reasons....

I agree with this point, but the last time I tried to find an example it was not very fruitful. If you have suggestions in which direction to look, I would be very happy.

**Comment by fabian-s** [comment]
> I agree with this point, but the last time I tried to find an example it was not very fruitful. If you have suggestions in which direction to look, I would be very happy.

image


well, we talked about this before, the course is starting soon and we want to wrap up so.... 
it's issue #493, for now.

**Pull request merged**
