### PR TITLE
Refactoring ex1 

### LINKED ISSUE #411: Improve exercise sheet day 1
- [x] Add exercise on "what is a model/learner" (`slides-basics-learners`)

Maybe something with `mlr3`, such as:

- How does a learner in `mlr3` compare to what you've learned in the videos?
- Pick an `mlr3` learner of your choice. What are the different settings for this learner?

---

- [x] Add formula for median in exercise 3 
> Show that the median is the best constant model with L1 loss.

- [x] Add more steps in solution for exercise 3 

---

- [x] Improve notation exercise 4 (KNN)

---

- [x] Rewrite exercise 5 so that mlr3 is used

- [x] Link to helpful help pages on mlr3 that can help the students to get started (they have at this point no knowledge on mlr3)

### PR DESCRIPTION
**Pull request by tpielok**
[exercise_1.pdf](https://github.com/compstat-lmu/lecture_i2ml/files/4039458/exercise_1.pdf)
[solution_1.pdf](https://github.com/compstat-lmu/lecture_i2ml/files/4030877/solution_1.pdf)

- [x] Add exercise on "what is a model/learner" (`slides-basics-learners`)

- [x] Add formula for median in exercise 3 

- [x] Add more steps in solution for exercise 3 
(made bigger changes to the solution, since the argumentation became faulty/unprecise in the end IMO)

- [x] Rewrite exercise 5 so that mlr3 is used

- [x] Link to helpful help pages on mlr3 that can help the students to get started (they have at this point no knowledge on mlr3)

closes #411

### CODE REVIEW

**Comment by HeidiSeibold** [comment]
Is the discussion in #411 already included in this PR?

**Comment by tpielok** [comment]
No, shall I add my last proof proposal then?

**Comment by HeidiSeibold** [comment]
Yes

**Comment by tpielok** [comment]
Done. (I've updated the pdfs in my fist comment)

**Comment by HeidiSeibold** [comment]
The `*` indicates "bonus exercise"?

**Comment by tpielok** [comment]
Yes, since solving the median exercise still takes some time, I thought it would be suitable to be a bonus exercise.

**Comment by HeidiSeibold** [comment]
Good, I think there should be a footnote saying that this is a bonus exercise.

**Comment by tpielok** [comment]
Done.

**Comment by HeidiSeibold** [comment]
Perfect, thanks!

**Pull request merged**
