### PR TITLE
Refactoring w1920

### PR DESCRIPTION
**Pull request by HeidiSeibold**
Please keep branch after merging, because not everything from refactoring is done (see #337).

### CODE REVIEW

**Comment by HeidiSeibold** [comment]
Looks like we could resolve the conflicts by first merging #460.

**Comment by HeidiSeibold** [comment]
I have no idea why the checks fail. On my machine `R CMD build . ` runs without issues.

**Comment by fabian-s** [comment]
:1st_place_medal: 

What a great effort, @HeidiSeibold, @RifatMehreen, @tpielok   -- thanks a lot a lot a lot!

- Website seems fine (except link to Team page which is weird but whatever, I fixed the automatic link generation to pdf-slides)
- code demos all compile
- slides (almost) all compile
- slides/slides-basics-notation did not compile -- mv'ed to attic because we'll have Rifat's cheatsheets anyways.

**exercises still need to be updated?**

**Comment by HeidiSeibold** [comment]
:tada: Thanks @fabian-s for merging.

Exercises are still under construction, but we need them only in March (they don't have to prepare them).

**Pull request merged**
