### PR TITLE
Delete files which are no longer in use

### PR DESCRIPTION
**Pull request by HeidiSeibold**
Do we just want to remove files no longer in use (accept PR) or move them somewhere (decline PR)?

In this PR I delete all files in folders called  `number-topic` (e.g. `09-bosting`) in main project folder.

### CODE REVIEW

**Comment by fabian-s** [comment]
i think we want this. this is why we use git.

**Comment by HeidiSeibold** [comment]
Ok, do we wait for feedback from @berndbischl or can we merge?

**Comment by fabian-s** [comment]
merged. curse me later, @berndbischl.

**Comment by berndbischl** [comment]
i guess this is fine. we have 2 options: have them in an attic-folder visible in the repo, or delete them, but keep issues open. i think @fabian-s did the latter right? 
then pls do NOT close the issues otherwise we lose the files.... although we dont use them now, it was still a lot of work to produce them in the first place...

**Pull request merged**
