### PR TITLE
fixes #420

### LINKED ISSUE #420: slides-classification-naivebayes: Remove unnecessary links to other slide
Should we try to be as modular as possible without hurting the content?

If so:
```
Another generative technique for categorical response $y \in \gset$ is called \emph{Naive Bayes classifier}.
```
->
```
\emph{Naive Bayes classifier} is a generative technique for categorical response $y \in \gset$.
```

https://github.com/compstat-lmu/lecture_i2ml/blob/refactoring-w1920/slides/supervised-classification/slides-classification-naivebayes.Rnw#L18

### PR DESCRIPTION
**Pull request by HeidiSeibold**

### CODE REVIEW

**Comment by HeidiSeibold** [comment]
@berndbischl you can remove this PR if you do not want to use it.

**Comment by fabian-s** [comment]
@berndbischl  ping

**Comment by fabian-s** [comment]
@berndbischl  did you want this? if not plz close

**Comment by fabian-s** [comment]
closing this since @berndbischl never replied and the conflicting material has been online for a while now

**Comment by berndbischl** [comment]
sorry... :(

**Pull request closed without merging**
