### PR TITLE
Rifat i2ml

### PR DESCRIPTION
**Pull request by RifatMehreen**
New slides for proximities for random forest

### CODE REVIEW

**Comment by fabian-s** [comment]
hi @RifatMehreen,

Thx for that, I have some suggestions/questions:

- in general we' d prefer more focused PRs, this one has both RF proximity stuff and nested CV figures, consider splitting stuff like that in the future, please, so that each PR adresses only one issue/task/chapter.
- in your commit messages, it would be helpful if you'd refer to the issues you're adressing (see https://github.blog/2011-04-09-issues-2-0-the-next-generation/#commits-issues). For example, an even better commit message for ea9a1b24b3b6994e5d652a4019a692513edeaab6 would have been 
`adds outer CV figures and link for editing. adresses #300`. 
- if you upload files directly to Github, please do edit the commit message to make it descriptive 

Re. the editable draw.io diagram:

If I open this in draw.io, the formatting is a little messed up (text not aligned etc):
 
image

is this a problem with Firefox/Linux? The diagram is displayed on google drive just fine.

(@schalkdaniel, @tpielok can you verify whether opening https://drive.google.com/file/d/1xjBfaPx5JDvjGt0p6E7Q-AGsrALLKcVC/view **in draw.io** works for you without messing up the formatting?)

The link is also "read-only" -- I can circumvent that by opening and editing a copy of the file, but I shouldn't have to.

Re. proximity slides:
- why are there two versions of these slides? please remove the one that is not meant for public consumption (with "git rm", simply deleting the file won't work....)
- please update the corresponding MAKEFILEs if you're adding slides (see my commit below)
- please do run a spell check before comitting new slides. 

Let me know if you have any questions, you can come by my office as well if you prefer -- I'm available all morning on Wednesday e.g.

**Comment by fabian-s** [comment]
PS: proximity slides are pretty great content-wise, thx a lot!

@berndbischl : 
do we really want to introduce MDS in this way?  (see attached slides)
seems like a quite advanced topic to just mention off-handedly like this? 
[slides-forests2_rand_prox_2.pdf](https://github.com/compstat-lmu/lecture_i2ml/files/3471681/slides-forests2_rand_prox_2.pdf)

**Comment by RifatMehreen** [comment]
@fabian-s Thank you for making things clear. I will make sure that things get done in this way. Also I will remove the previous slide of proximities.

**Comment by fabian-s** [comment]
meeting today:

- use draw.io, export as SVG and save the draw.io link (editable)
- figure out placement of outer CV diagram

**Pull request closed without merging**
