### PR TITLE
Refactoring ex2 tobi

### PR DESCRIPTION
**Pull request by tpielok**
Improve exercises 3 and 4

[solution_2.pdf](https://github.com/compstat-lmu/lecture_i2ml/files/3979011/solution_2.pdf)
[exercise_2.pdf](https://github.com/compstat-lmu/lecture_i2ml/files/4096684/exercise_2.pdf)

reference #425

### CODE REVIEW

**Comment by HeidiSeibold** [comment]
Can all boxes in #423 be checked? @tpielok please do so if this is the case and ping me here again to review. Thanks!

**Comment by tpielok** [comment]
I did check all except ex2 since plotLearnerPrediction() has to be implemented in mlr3 first.
@HeidiSeibold

**Comment by HeidiSeibold** [comment]
Any updates on `plotLearnerPrediction()`? Will this be available on time?

**Comment by tpielok** [comment]
Done and ready for merge @HeidiSeibold.

**Pull request merged**
