### PR TITLE
Code demos day 1 mlr2 -> mlr3

### PR DESCRIPTION
**Pull request by tpielok**
- [x] limo
~~@fabian-s could you check if this compiles to pdf for you? I'm not sure why this does not compile on my machine.~~
- [x] knn

- [x] splines (no mlr3 in here)

### CODE REVIEW

**Comment by fabian-s** [comment]
@tpielok 

worked for me after I deleted the `_cache` and `_files` directories and recompiled?

I think there might have been a weird interaction between knitr's caching system and {mlr3} / {paradox} defining a `c` method for `ParamSet` which are also environments (...R6). 

as far as I can tell, knitr tried to add something to an environment in the database that represents its cache (?), but that then called this method for ParamSets and then it shit its pants:
```r
> options(error = recover)
> rmarkdown::render("code_demo_limo.Rmd")


processing file: code_demo_limo.Rmd
  |...                                                    |   6%
  ordinary text without R code

  |......                                                 |  12%
label: limo-preamble (with options) 
List of 3
 $ child  : chr "../style/preamble_code_demos.Rmd"
 $ include: logi FALSE
 $ purl   : logi FALSE

[......]

  |.............................................          |  82%
label: grad_desc_mlr
Quitting from lines 273-282 (code_demo_limo.Rmd) 
Error in do.call(makeParamSet, pars) : second argument must be a list

Enter a frame number, or 0 to exit   

 1: rmarkdown::render("code_demo_limo.Rmd")
 2: knitr::knit(knit_input, knit_output, envir = envir, quiet = 
 3: process_file(text, output)
 4: withCallingHandlers(if (tangle) process_tangle(group) else p
 5: process_group(group)
 6: process_group.block(group)
 7: call_block(x)
 8: block_exec(params)
 9: block_cache(options, output, objs)
10: cache$save(objects, outname, hash, lazy = options$cache.lazy
11: getFromNamespace("makeLazyLoadDB", "tools")(knit_global(), p
12: lazyLoadDBinsertVariable(vars[i], from, datafile, ascii, com
13: (function (e) 
{
    if (is.environment(e)) {
        name <
14: lazyLoadDBinsertValue(data, datafile, ascii, compress, envho
15: (function (e) 
{
    if (is.environment(e)) {
        name <
16: lazyLoadDBinsertValue(data, datafile, ascii, compress, envho
17: (function (e) 
{
    if (is.environment(e)) {
        name <
18: lazyLoadDBinsertValue(data, datafile, ascii, compress, envho
19: (function (e) 
{
    if (is.environment(e)) {
        name <
20: lazyLoadDBinsertValue(data, datafile, ascii, compress, envho
21: (function (e) 
{
    if (is.environment(e)) {
        name <
22: table$insert(e)
23: c(e, envs)
24: c.ParamSet(e, envs)
25: do.call(makeParamSet, pars)
```

does not explain why even repeated renders now work after cleaning the old cache..
who knows :man_shrugging:

**Comment by tpielok** [comment]
mlr3 and rmarkdown do not seem to be best buddies...

> I think there might have been a weird interaction between knitr's caching system and {mlr3} / {paradox} defining a `c` method for `ParamSet` which are also environments (...R6). 

(I think this could be a problem here again)

This time clearing the cache, unfortunately, does not fix the problem:
I created a [gist](https://gist.github.com/tpielok/d8b58345dc1de54549677f9765b02ece) with the relevant mlr3 code of the knn code demo.

First run:
```r
> options(error = recover)
> rmarkdown::render("knn.Rmd")


processing file: knn.Rmd
  |......                                                           |  10%
  ordinary text without R code

[...]
 
  |....................................................             |  80%
label: knn-mlr-1
  |..........................................................       |  90%
  ordinary text without R code

  |.................................................................| 100%
label: knn-mlr-2
Quitting from lines 47-56 (knn.Rmd) 
Error in c.PredictionClassif(e, envs) : 
  Assertion on 'dots' failed: May only contain the following types: {PredictionClassif}, but element 2 has type 'NULL'.

Enter a frame number, or 0 to exit   

 1: rmarkdown::render("knn.Rmd")
 2: knitr::knit(knit_input, knit_output, envir = envir, quiet = 
 3: process_file(text, output)
 4: withCallingHandlers(if (tangle) process_tangle(group) else p
 5: process_group(group)
 6: process_group.block(group)
 7: call_block(x)
 8: block_exec(params)
 9: block_cache(options, output, objs)
10: cache$save(objects, outname, hash, lazy = options$cache.lazy
11: getFromNamespace("makeLazyLoadDB", "tools")(knit_global(), p
12: lazyLoadDBinsertVariable(vars[i], from, datafile, ascii, com
13: (function (e) 
{
    if (is.environment(e)) {
        name <
14: table$insert(e)
15: c(e, envs)
16: c.PredictionClassif(e, envs)
17: assert_list(dots, "PredictionClassif")
18: makeAssertion(x, res, .var.name, add)
19: mstop("Assertion on '%s' failed: %s.", var.name, res, call.
```
Afterwards: 
```r
> rmarkdown::render("knn.Rmd")


processing file: knn.Rmd
  |......                                                           |  10%
  ordinary text without R code

 [...]
  |.................................................................| 100%
label: knn-mlr-2
Quitting from lines 47-56 (knn.Rmd) 
Error: Cannot predict, Learner 'classif.kknn' has not been trained yet
```

Does this happen for you, too?
Strangely errors like this did not occur in the Rnw files.

**Comment by tpielok** [comment]
New observation: as probably expected with `cache = FALSE` it compiles [code without cache](https://gist.github.com/tpielok/f72586461bce966e8fec4f1df7f64c61)

**Comment by fabian-s** [comment]
yeah, happens to me too. 

easy but time-consuming fix: switch off caching for mlr3 related chunks. 
see https://github.com/mlr-org/mlr3/issues/438

**Comment by tpielok** [comment]
I just found this, seems to be a *feature* https://github.com/mlr-org/mlr3/wiki/FAQ

**Comment by fabian-s** [comment]
aaah, you so smart!

**Comment by fabian-s** [comment]
pls fix our Rmd-headers accordingly.

**Comment by tpielok** [comment]
Done. @fabian-s

**Comment by fabian-s** [comment]
thx @tpielok

**Pull request merged**
